heat_template_version: 2021-04-16
description: sigi cloud (bravo)

outputs:

  bravo_public_ip:
    value: { get_attr: [bravo_public_ip, floating_ip_address] }

resources:

  bravo_server:
    type: OS::Nova::Server
    properties:
      flavor: m2a.large
      key_name: { get_resource: bravo_keypair }
      networks:
        - subnet: { get_resource: bravo_subnet }
          floating_ip: { get_resource: bravo_public_ip }
      security_groups:
        - { get_resource: bravo_sg }
      block_device_mapping_v2:
        - volume_id: { get_resource: bravo_volume }

  bravo_volume:
    type: OS::Cinder::Volume
    properties:
      image: Ubuntu-22.04
      size: 25 # GB

  bravo_public_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: PublicStatic

  bravo_network:
    type: OS::Neutron::Net

  bravo_subnet:
    type: OS::Neutron::Subnet
    properties:
      cidr: 192.168.0.0/24
      network: { get_resource: bravo_network }
      dns_nameservers: [ 8.8.8.8, 8.8.4.4 ]

  bravo_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: PublicStatic

  bravo_router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: bravo_router }
      subnet: { get_resource: bravo_subnet }

  bravo_sg:
    type: OS::Neutron::SecurityGroup

  honbu_sg_rule:
    type: OS::Neutron::SecurityGroupRule
    properties:
      description: "本部"
      direction: ingress
      port_range_max: 22
      port_range_min: 22
      protocol: tcp
      remote_ip_prefix: '73.181.206.101/32'
      security_group: { get_resource: bravo_sg }

  whitehouse_sg_rule:
    type: OS::Neutron::SecurityGroupRule
    properties:
      description: whitehouse
      direction: ingress
      port_range_max: 22
      port_range_min: 22
      protocol: tcp
      remote_ip_prefix: '74.122.141.153/32'
      security_group: { get_resource: bravo_sg }

  bravo_keypair:
    type: OS::Nova::KeyPair
    properties:
      name: 2024-09-11-sigi-bravo-key
      public_key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMcCETGoN4EyyPYPQ9O0K8z5Zs1MpRVk3yP8tadCOoKo justinhill@Justins-MacBook-Pro.local'
